select a.skill_name
    from (values
        ('python')
        , ('sql')
        , ('airflow')
        , ('apache airflow')
        , ('dbt')
        , ('postgresql')
        , ('etl')
        , ('dwh')
        , ('linux')
        , ('английский язык')
        , ('english')
        , ('ms sql')
        , ('git')
        , ('базы данных')
        , ('docker')
        , ('ssis')
        , ('tableau')
        , ('power bi')
        , ('ms sql server')
        , ('data warehouse')
        , ('анализ данных')
        , ('pandas')
    ) as a(skill_name)