@startuml
title: SuperStore conceptual data model
fact_orders }|--|| dim_customers
fact_orders }|-right-|| dim_addresses
fact_orders }|-up-|| dim_products
fact_orders }|-left-|| dim_dates
fact_orders }|-left-|| dim_dates
fact_orders }|--|| dim_ship_modes
@enduml